export { default as Home } from './Home'
export { default as Logon } from './Logon'
export { default as Plans } from './Plans'
export { default as Register } from './Register'
export { default as Registration } from './Registration'
export { default as Settings } from './Settings'
export { default as Students } from './Students'
