export default {
	SET_TOKEN: 'SESSION/SET_TOKEN',
	SET_USER: 'SESSION/SET_USER',
	SET_LOADING: 'SESSION/SET_LOADING',
	SET_ERRORS: 'SESSION/SET_ERRORS',
	REMOVE_TOKEN: 'SESSION/REMOVE_TOKEN',
	REMOVE_USER: 'SESSION/REMOVE_USER',
	REMOVE_LOADING: 'SESSION/REMOVE_LOADING',
	REMOVE_ERRORS: 'SESSION/REMOVE_ERRORS',
}
