export default {
	SET_PLAN: 'PLAN/SET_PLAN',
	SET_PLANS: 'PLAN/SET_PLANS',
	SET_LOADING: 'PLAN/SET_LOADING',
	REMOVE_PLAN: 'PLAN/REMOVE_PLAN',
	REMOVE_PLANS: 'PLAN/REMOVE_PLANS',
	REMOVE_LOADING: 'PLAN/REMOVE_LOADING',
	FILTER_PLANS: 'PLAN/FILTER_PLANS',
	PUSH_PLAN: 'PLAN/PUSH_PLAN',
}
