export default {
	SET_STUDENT: 'STUDENT/SET_STUDENT',
	SET_STUDENTS: 'STUDENT/SET_STUDENTS',
	SET_LOADING: 'STUDENT/SET_LOADING',
	REMOVE_STUDENT: 'STUDENT/REMOVE_STUDENT',
	REMOVE_STUDENTS: 'STUDENT/REMOVE_STUDENTS',
	REMOVE_LOADING: 'STUDENT/REMOVE_LOADING',
}
